os: Visual Studio 2015

version: 1.0.3.{build}

configuration:
- Debug
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- ps: Start-FileDownload 'https://download.microsoft.com/download/0/A/3/0A372822-205D-4A86-BFA7-084D2CBE9EDF/DotNetCore.1.0.1-SDK.1.0.0.Preview2-003133-x64.exe'
- cmd: DotNetCore.1.0.1-SDK.1.0.0.Preview2-003133-x64.exe /quiet

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- appveyor-retry dotnet restore .\src\XPath2 -v Minimal
- appveyor-retry dotnet restore .\src\XPath2.Extensions -v Minimal
- appveyor-retry dotnet restore .\tests\XPath2.Extensions.Tests -v Minimal
- appveyor-retry nuget restore .\src\XQTSRun\XQTSRun.csproj -PackagesDirectory packages

- dotnet build .\src\XPath2\project.json -c %CONFIGURATION%
- dotnet build .\src\XPath2.Extensions\project.json -c %CONFIGURATION%
- dotnet build .\tests\XPath2.Extensions.Tests\project.json -c %CONFIGURATION%
- cmd: msbuild .\src\XQTSRun\XQTSRun.csproj /p:Configuration=%CONFIGURATION% /p:Platform=AnyCPU

- dotnet pack -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o .\artifacts .\src\XPath2\project.json
- dotnet pack -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o .\artifacts .\src\XPath2.Extensions\project.json

test_script:
- dotnet test -c %CONFIGURATION% --no-build .\tests\XPath2.Extensions.Tests

artifacts:
- path: artifacts\**\*.*

cache:
- packages