os: Visual Studio 2017

version: 1.0.6.{build}

configuration:
- Debug

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-gs-x64.exe'
  - cmd: dotnet-sdk-2.0.0-win-gs-x64.exe /quiet
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- dotnet restore .\src\XPath2\XPath2.csproj
- dotnet restore .\src\XPath2.Extensions\XPath2.Extensions.csproj
- dotnet restore .\tests\XPath2.Extensions.Tests\XPath2.Extensions.Tests.csproj
- nuget restore .\src\XQTSRun\XQTSRun.csproj

- dotnet build .\src\XPath2\XPath2.csproj -c %CONFIGURATION%
- dotnet build .\src\XPath2.Extensions\XPath2.Extensions.csproj -c %CONFIGURATION%
- dotnet build .\tests\XPath2.Extensions.Tests\XPath2.Extensions.Tests.csproj -c %CONFIGURATION%
- cmd: msbuild .\src\XQTSRun\XQTSRun.csproj /p:Configuration=%CONFIGURATION% /p:Platform=AnyCPU

after_test:
  - nuget.exe install OpenCover -ExcludeVersion
  - nuget.exe install coveralls.net -ExcludeVersion -Version 0.7.0
  - pip install codecov

  - cmd: '"OpenCover\tools\OpenCover.Console.exe" -target:dotnet.exe -targetargs:"test tests\XPath2.Extensions.Tests\XPath2.Extensions.Tests.csproj --no-build" -filter:"+[XPath2]* +[XPath2.Extensions]* -[*Tests*]*" -output:coverage.xml -register:user -oldStyle -searchdirs:".\tests\XPath2.Extensions.Tests\bin\%CONFIGURATION%\net452"'
  - codecov -f "coverage.xml"
  - coveralls.net\tools\csmacnz.Coveralls.exe --opencover -i .\coverage.xml
